services:
  api:
    platform: linux/x86_64
    image: emahnovets/menu-app-api
    ports:
      - "3000:3000"
    env_file: api.env
    depends_on:
      db:
        condition: service_healthy

  db:
    platform: linux/x86_64
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    env_file: db.env
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 10
