name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Generate env files
        env:
          DB_PASS: ${{ secrets.TEST_DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.TEST_JWT_SECRET }}
          ADMIN_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          ADMIN_PASS: ${{ secrets.TEST_USER_PASSWORD }}
        run: npm run gen:env
      - name: Start API
        run: npm run api:start
      - name: Check API logs
        run: |
          docker ps -a
      - name: Cypress run
        uses: cypress-io/github-action@v2
        env:
          CYPRESS_TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
          CYPRESS_TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
        with:
          build: npm run build:ci
          start: npm run start:ci
      - name: Save screenshots and videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos
